version: '3.3'

# =========================================
# X-Templates
# =========================================
x-service: &service
  image: moleculer
  build:
    context: .
    dockerfile: Dockerfile
  env_file: .env
  restart: unless-stopped

services:

  api:
    <<: *service
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - nats
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-sv.entrypoints=https
      - traefik.http.routers.api-sv.rule=Host(`api.${DOMAIN:-example.com}`)
      - traefik.http.services.api-sv.loadbalancer.server.port=3000
      - traefik.http.routers.api-sv.tls.certresolver=mycert
      - traefik.http.routers.api-sv.tls.domains[0].main=api.${DOMAIN:-example.com}
    networks:
      - proxy-net
      - redis-net
      - nats-net

  greeter:
    <<: *service
    environment:
      SERVICES: greeter
    depends_on:
      - nats
      - redis
    networks:
      - redis-net
      - nats-net

  products:
    <<: *service
    environment:
      SERVICES: products
    depends_on:
      - mongo
      - nats
      - redis
    networks:
      - mongo-net
      - redis-net
      - nats-net
